// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:111165214207:web:9937665f3b16838969abca',
    messagingSenderId: '111165214207',
    projectId: 'mobile-ar-tourism',
    authDomain: 'mobile-ar-tourism.firebaseapp.com',
    storageBucket: 'mobile-ar-tourism.appspot.com',
    measurementId: 'G-QEX5FSDLM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:111165214207:android:00d70103ff613b4869abca',
    messagingSenderId: '111165214207',
    projectId: 'mobile-ar-tourism',
    storageBucket: 'mobile-ar-tourism.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:111165214207:ios:d4305e466317323869abca',
    messagingSenderId: '111165214207',
    projectId: 'mobile-ar-tourism',
    storageBucket: 'mobile-ar-tourism.appspot.com',
    androidClientId: '111165214207-nqq0sfbeakqstllr27q1h0247o1tuara.apps.googleusercontent.com',
    iosClientId: '111165214207-pa3dk7pbiord2g6i38edo5r3t04qrhce.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileArTourism',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:111165214207:ios:cd9e4b63497824d869abca',
    messagingSenderId: '111165214207',
    projectId: 'mobile-ar-tourism',
    storageBucket: 'mobile-ar-tourism.appspot.com',
    androidClientId: '111165214207-nqq0sfbeakqstllr27q1h0247o1tuara.apps.googleusercontent.com',
    iosClientId: '111165214207-4p1hvrjuhh7vtphi5okimff3i6ugjghu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileArTourism.RunnerTests',
  );
}
